---
language: node_js

node_js:
  - "5"

sudo: false

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"

install:
  - npm install -g bower
  - npm install
  - bower install

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    npm run doc
    cd docs
    git init
    git checkout -b gh-pages
    git add .
    git -c user.name='Travis CI' -c user.email='info@travis-ci.org' commit -m "Update docs"
    git push -f -q https://$GITHUB_API_KEY@github.com/anehx/anonboard-frontend.git gh-pages >/dev/null 2>&1
    cd "$TRAVIS_BUILD_DIR"
  fi

script:
  - npm test

notifications:
  email:
    - jonasmetzener@gmail.com
