---
language: node_js

node_js:
  - "5"

sudo: false

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"

install:
  - npm install -g bower
  - npm install
  - bower install

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - npm test

notifications:
  email:
    - jonasmetzener@gmail.com
